name: docuxtract-services

services:
  orchestrator:
    container_name: orchestrator
    depends_on:
      - rabbitmq
      - postgres
    build:
      context: .
      dockerfile: ./apps/orchestrator/Dockerfile.dev
    command: pnpm start:dev orchestrator
    env_file:
      - ./apps/orchestrator/.env
    volumes:
      - ./libs:/app/libs
      - ./apps/orchestrator:/app/apps/orchestrator
      # - /app/node_modules
    ports:
      - 3000:3000
      - 9230:9229
  
  email-int:
    container_name: email-int
    depends_on:
      - rabbitmq
      - postgres
    build:
      context: .
      dockerfile: ./apps/email-int/Dockerfile.dev
    command: pnpm start:dev email-int
    env_file:
      - ./apps/email-int/.env
    volumes:
      - ./apps/email-int:/app/apps/email-int
      - ./libs:/app/libs
      # - /app/node_modules
    ports:
      - 3001:3000
      - 9231:9229
  