# name: common

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
      - 15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
      - rabbitmqlog:/var/log/rabbitmq
    networks:
      - services-net

  postgres:
    container_name: postgres
    image: postgres:17
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - services-net

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - orchestrator
      - crm-int
    networks:
      - services-net

volumes:
  pgdata:
  rabbitmqdata:
  rabbitmqlog:

networks:
  services-net:
    driver: bridge