name: docuxtract-services

services:
  user-management:
    container_name: user-management
    depends_on:
      - rabbitmq
      - postgres
    build:
      context: .
      dockerfile: ./apps/user-management/Dockerfile.dev
    command: pnpm start:debug user-management
    env_file:
      - ./apps/user-management/.env
    volumes:
      - ./libs:/app/libs
      - ./apps/user-management:/app/apps/user-management
    ports:
      - 9230:9229
    networks:
      - services-net

  orchestrator:
    container_name: orchestrator
    depends_on:
      - rabbitmq
      - postgres
    build:
      context: .
      dockerfile: ./apps/orchestrator/Dockerfile.dev
    command: pnpm start:debug orchestrator
    env_file:
      - ./apps/orchestrator/.env
    volumes:
      - ./libs:/app/libs
      - ./apps/orchestrator:/app/apps/orchestrator
    ports:
      - 9231:9229
    networks:
      - services-net
  
  email-int:
    container_name: email-int
    depends_on:
      - rabbitmq
      - postgres
    build:
      context: .
      dockerfile: ./apps/email-int/Dockerfile.dev
    command: pnpm start:debug email-int
    env_file:
      - ./apps/email-int/.env
    volumes:
      - ./apps/email-int:/app/apps/email-int
      - ./libs:/app/libs
    ports:
      - 9232:9229
    networks:
      - services-net
  
  crm-int:
    container_name: crm-int
    depends_on:
      - rabbitmq
      - postgres
    build:
      context: .
      dockerfile: ./apps/crm-int/Dockerfile.dev
    command: pnpm start:debug crm-int
    env_file:
      - ./apps/crm-int/.env
    volumes:
      - ./apps/crm-int:/app/apps/crm-int
      - ./libs:/app/libs
    ports:
      - 9233:9229
    networks:
      - services-net
  
  feedback:
    container_name: feedback
    depends_on:
      - rabbitmq
      - postgres
    build:
      context: .
      dockerfile: ./apps/feedback/Dockerfile.dev
    env_file:
      - ./apps/feedback/.env
    volumes:
      - ./apps/feedback:/app/apps/feedback
      - ./libs:/app/libs
    ports:
      - 9234:9229
    networks:
      - services-net
  
  payment:
    container_name: payment
    depends_on:
      - rabbitmq
      - postgres
    build:
      context: .
      dockerfile: ./apps/payment/Dockerfile.dev
    env_file:
      - ./apps/payment/.env
    volumes:
      - ./apps/payment:/app/apps/payment
      - ./libs:/app/libs
    ports:
      - 9235:9229
    networks:
      - services-net
  