name: docuxtract-services

services:
  auth:
    container_name: auth
    depends_on:
      - rabbitmq
      - postgres
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile.dev
    command: pnpm start:debug auth
    env_file:
      - ./apps/auth/.env
    volumes:
      - ./libs:/app/libs
      - ./apps/auth:/app/apps/auth
    ports:
      - 3000:3000
      - 9230:9229
    networks:
      - services-net

  orchestrator:
    container_name: orchestrator
    depends_on:
      - rabbitmq
      - postgres
    build:
      context: .
      dockerfile: ./apps/orchestrator/Dockerfile.dev
    command: pnpm start:debug orchestrator
    env_file:
      - ./apps/orchestrator/.env
    volumes:
      - ./libs:/app/libs
      - ./apps/orchestrator:/app/apps/orchestrator
    ports:
      - 3001:3000
      - 9231:9229
    networks:
      - services-net
  
  email-int:
    container_name: email-int
    depends_on:
      - rabbitmq
      - postgres
    build:
      context: .
      dockerfile: ./apps/email-int/Dockerfile.dev
    command: pnpm start:debug email-int
    env_file:
      - ./apps/email-int/.env
    volumes:
      - ./apps/email-int:/app/apps/email-int
      - ./libs:/app/libs
    ports:
      - 3002:3000
      - 9232:9229
    networks:
      - services-net
  
  crm-int:
    container_name: crm-int
    depends_on:
      - rabbitmq
      - postgres
    build:
      context: .
      dockerfile: ./apps/crm-int/Dockerfile.dev
    command: pnpm start:debug crm-int
    env_file:
      - ./apps/crm-int/.env
    volumes:
      - ./apps/crm-int:/app/apps/crm-int
      - ./libs:/app/libs
    ports:
      - 3003:3000
      - 9233:9229
    networks:
      - services-net
  