# name: common

services:
  ms-rabbitmq:
    container_name: ms-rabbitmq
    image: rabbitmq:4-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
      - 15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
      - rabbitmqlog:/var/log/rabbitmq
    networks:
      - ms-services-net

  ms-postgres:
    container_name: ms-postgres
    image: postgres:17
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ms-services-net

  ms-nginx:
    container_name: ms-nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
<<<<<<< Updated upstream
      - orchestrator
      - crm-int
      - feedback
      - payment
      - auth
=======
      - ms-orchestrator
      - ms-crm-int
      - ms-feedback
      - ms-payment
      - ms-user-management
>>>>>>> Stashed changes
    networks:
      - ms-services-net
  
  ms-ngrok:
    container_name: ms-ngrok
    image: ngrok/ngrok:alpine
    restart: unless-stopped
    env_file:
      - ./.env
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    depends_on:
      - ms-nginx
    networks:
      - ms-services-net

volumes:
  pgdata:
  rabbitmqdata:
  rabbitmqlog:

networks:
  ms-services-net:
    driver: bridge